apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.name }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.name }}"
  replicas: {{ int .Values.replicas }}
  template:
    metadata:
      labels:
        app: "{{ .Values.name }}"
    spec:
      containers:
      - name: "{{ .Values.name }}"
        image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
        ports:
        - containerPort: 8080