name: CI/CD Pipeline
on:
  #Manually trigger workflow runs
  workflow_dispatch:
  #Trigger the workflow on push from the master branch
  push:
    branches:
      - master
      #update
jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 

      - name: Checkout
        uses: actions/checkout@v3

#/////////////////////////////////////////////////////////
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            apizzulli/spring-docker
          tags: #
            # type=ref,event=branch
            # type=semver,pattern={{version}}
            # type=semver,pattern={{major}}.{{minor}}
          flavor: |
            latest=true

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: apizzulli
          password: dckr_pat_82tPTNM101mSleh-2f7Ig_Bhv3M
#///////////////////////////////////////////////////////////

#testing1
      - name: Build and push
        id: Build_and_push
        uses: docker/build-push-action@v3
        with: 
          run: cd ../
               cd ../
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          #labels: ${{ steps.meta.outputs.labels }}

      - name: Springboot Pipeline
        uses: actions/checkout@v1
      #Set up JDK 11
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          #comments

      #Run Tests
      - name: Run Tests
        run: mvn -B test
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      #Set up Maven cache
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=apizzulli_spring-cicd-demo

